name: plugin
version: 0.1
main: meowland.Main
author: KotMilkMeoW
commands:
   hi:
      description: i
      permission: <plugin name>.hi
      usage: /command
   sword: 
      description: give sword
      permission: <plugin name>.hi
      usage: /command
